[package]
name = "vibe-clip"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.6.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
regex = "1.0"
rand = "0.9.2"
